development:
  adapter: postgresql
  encoding: unicode
  database: beautiflow_development
  host: localhost
  pool: 5
  username: postgres
  password: mateo525

production:
  adapter: postgresql
  encoding: unicode
  database: beautiflow_development
  host: localhost
  pool: 5
  username: postgres
  password: mateo525